### ISSUE TITLE
Crypto-backed certificates?

### ISSUE THREAD

**Issue by rht** [edx/credentials#139]
(needs correction) AFAIU, currently the course certifications forEach learner are stored in a (mutable) SQLdb in a server farm (somewhere amazon-knows-where). How can this be made more accountable?

Given such case, Would it be possible to issue a key-pair, where either 1. the public key forEach learner is augmented for each additional course certification, or 2. use a more ZKP scheme to prove just the required course cert to the other party.

Would be even better if the proof can be done offline anywhere, so it could replace a stamped/hand-signed piece of paper once for all.

**Comment by clintonb** [comment]
Exactly what problem are you trying to solve?

**Comment by rht** [comment]
It is regarding with https://www.edx.org/verified-certificate -- how can *anyone* do an offline verification, at any time, that such document with such document id represents the content on it.

**Comment by rht** [comment]
As per https://github.com/edx/edx-platform/blob/adad6b2e836b8035517e2ee0dc6d57250ddbc6b6/CONTRIBUTING.rst guideline, I should raise the issue at either the JIRA tracker (https://openedx.atlassian.net/secure/Dashboard.jspa) or the mailing list (https://groups.google.com/forum/#!forum/edx-code). I have since rediscovered an implementation by http://www.blockcerts.org/ (which additionally pushes the cert to a public ledger!). //brb
